"""
Gemini LLM Adapter
Wraps the Google GenAI SDK for structured text generation.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
from pathlib import Path
from typing import Type, TypeVar

from dotenv import load_dotenv
from google import genai
from google.genai import types
from pydantic import BaseModel, ValidationError

from adapters.base import BaseLLMAdapter, LLMAdapterError

_PROJECT_ROOT = Path(__file__).parent.parent
load_dotenv(_PROJECT_ROOT / ".env")

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)

_DEFAULT_TEMPERATURE = 0.7
_DEFAULT_MAX_TOKENS = 8192
_MAX_RETRIES = 3
_RETRY_BASE_DELAY = 2.0


def _strip_unsupported_schema_fields(schema: dict) -> dict:
    """
    Recursively remove schema fields unsupported by Gemini API.
    
    Gemini API does not support:
    - 'additionalProperties' (generated by Pydantic for strict validation)
    - 'prefixItems' (generated by Pydantic for tuple types)
    
    When 'prefixItems' is removed from an array schema, we add a generic
    'items' field to satisfy Gemini's requirement that arrays have item schemas.
    """
    if not isinstance(schema, dict):
        return schema
    
    cleaned = {}
    has_prefix_items = False
    prefix_items_value = None
    
    for key, value in schema.items():
        if key == "additionalProperties":
            continue
        elif key == "prefixItems":
            has_prefix_items = True
            prefix_items_value = value
            continue
        elif isinstance(value, dict):
            cleaned[key] = _strip_unsupported_schema_fields(value)
        elif isinstance(value, list):
            cleaned[key] = [
                _strip_unsupported_schema_fields(item) if isinstance(item, dict) else item
                for item in value
            ]
        else:
            cleaned[key] = value
    
    if has_prefix_items and "items" not in cleaned and prefix_items_value:
        if isinstance(prefix_items_value, list) and len(prefix_items_value) > 0:
            cleaned["items"] = _strip_unsupported_schema_fields(prefix_items_value[0])
        else:
            cleaned["items"] = {}
    
    return cleaned


class GeminiLLMAdapter(BaseLLMAdapter):
    """
    Google Gemini implementation of BaseLLMAdapter.
    
    Supports structured (JSON-schema-constrained) responses that are
    automatically parsed and validated against Pydantic V2 models.
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str | None = None,
    ) -> None:
        from config import Config
        
        resolved_key = api_key or Config.GOOGLE_API_KEY
        if not resolved_key:
            raise LLMAdapterError(
                "Google API key not found. "
                "Set GOOGLE_API_KEY in .env or pass api_key parameter."
            )
        self._client = genai.Client(api_key=resolved_key)
        self._model = model or Config.GEMINI_TEXT_MODEL

    async def generate_structured_response(
        self,
        prompt: str,
        response_schema: Type[T],
        system_instruction: str | None = None,
        temperature: float = _DEFAULT_TEMPERATURE,
        max_output_tokens: int = _DEFAULT_MAX_TOKENS,
    ) -> T:
        raw_schema = response_schema.model_json_schema()
        cleaned_schema = _strip_unsupported_schema_fields(raw_schema)
        
        config = types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=cleaned_schema,
            temperature=temperature,
            max_output_tokens=max_output_tokens,
            system_instruction=system_instruction,
        )

        last_exc: Exception | None = None
        for attempt in range(1, _MAX_RETRIES + 1):
            try:
                response = await self._client.aio.models.generate_content(
                    model=self._model,
                    contents=[prompt],
                    config=config,
                )
                return self._parse_response(response, response_schema)

            except LLMAdapterError:
                raise

            except Exception as exc:
                last_exc = exc
                if attempt < _MAX_RETRIES:
                    delay = _RETRY_BASE_DELAY ** attempt
                    logger.warning(
                        "LLM call failed (attempt %d/%d): %s — retrying in %.1fs",
                        attempt,
                        _MAX_RETRIES,
                        exc,
                        delay,
                    )
                    await asyncio.sleep(delay)

        raise LLMAdapterError(
            f"LLM call failed after {_MAX_RETRIES} retries. Last error: {last_exc}"
        ) from last_exc

    async def generate_raw(
        self,
        prompt: str,
        system_instruction: str | None = None,
        temperature: float = _DEFAULT_TEMPERATURE,
        max_output_tokens: int = _DEFAULT_MAX_TOKENS,
    ) -> str:
        config = types.GenerateContentConfig(
            temperature=temperature,
            max_output_tokens=max_output_tokens,
            system_instruction=system_instruction,
        )
        try:
            response = await self._client.aio.models.generate_content(
                model=self._model,
                contents=[prompt],
                config=config,
            )
            return response.text or ""
        except Exception as exc:
            raise LLMAdapterError(f"Raw LLM call failed: {exc}") from exc

    @staticmethod
    def _parse_response(response, response_schema: Type[T]) -> T:
        parsed_attr = getattr(response, "parsed", None)
        if parsed_attr is not None:
            if isinstance(parsed_attr, response_schema):
                return parsed_attr
            try:
                return response_schema.model_validate(parsed_attr)
            except ValidationError:
                pass

        raw_text: str = response.text or ""

        try:
            return response_schema.model_validate_json(raw_text)
        except (ValidationError, ValueError):
            pass

        match = re.search(r"\{.*\}", raw_text, re.DOTALL)
        if match:
            try:
                return response_schema.model_validate_json(match.group())
            except (ValidationError, ValueError) as exc:
                raise LLMAdapterError(
                    f"Schema validation failed for {response_schema.__name__}: {exc}\n"
                    f"Raw LLM output:\n{raw_text[:500]}"
                ) from exc

        raise LLMAdapterError(
            f"Could not extract valid JSON for {response_schema.__name__} "
            f"from LLM response:\n{raw_text[:500]}"
        )
